# WARNING - Generated by {fusen} from dev/fusen_fct_nbastatR.Rmd: do not edit by hand

test_that("get_match_day works", {
  matchs_24102023 <- get_match_day(as.Date("2023-10-24"))
  expect_equal(nrow(matchs_24102023), 4)
  expect_equal(names(matchs_24102023), 
               c("dateGame", "slugTeam", "numberGameDate", "idGame", "idTeam", 
                 "pctFG", "pctFT", "pctFG3", "nameTeam", "cityTeam", "teamName", 
                 "recordOverall", "ptsQ1", "ptsQ2", "ptsQ3", "ptsQ4", "ptsOT1", 
                 "ptsOT2", "ptsOT3", "ptsOT4", "ptsOT5", "ptsOT6", "ptsOT7", "ptsOT8", 
                 "ptsOT9", "ptsOT10", "pts", "ast", "treb", "tov"))
})
