# WARNING - Generated by {fusen} from dev/fusen_fct_nbastatR.Rmd: do not edit by hand

#' Récupération des matchs d'un jour souhaité
#'
#' @param game_dates (Date) les dates des jours souhaités
#'
#' @return (dfr) table des matchs des dates souhaitées
#' @export
#'
#' @importFrom nbastatR days_scores
#' @importFrom dplyr filter pull
#'
#' @examples
#' get_match_day()
get_match_day <- function(game_dates = Sys.Date()){
  days_scores(game_dates = game_dates,
              league = "NBA") %>%
    filter(nameTable == "LineScore") %>%
    pull(dataTable) %>% .[[1]]
}
