on:
  push:
    branches: master

jobs:
  render-rmd:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::lubridate
            any::tidyr
            any::rmarkdown
            any::devtools
            github::abresler/nbastatR

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render rmd
        run: Rscript -e 'rmarkdown::render("dev/rmd_statsNBA.Rmd",output_dir = "docs",output_file = "index.html")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/index.html
          git commit -m 'update data rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
