name: "Update données pour matchs du jour"
on:
  push:
    branches: master

jobs:
  render-rmd:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::lubridate
            any::tidyr
            any::rmarkdown
            any::devtools
            any::here
            any::DT
            any::config
            any::golem
            any::shiny
            any::shinybusy
            any::shinyWidgets
            github::abresler/nbastatR

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get --yes install --no-install-recommends openvpn
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Connect to ProtonVPN
        run: vpn/connect.sh vpn/config.ovpn
        env:
          VPN_USERNAME: ${{ secrets.PROTONVPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.PROTONVPN_PASSWORD }}
          VPN_ROOT_CERT: ${{ secrets.PROTONVPN_ROOT_CERT }}
          VPN_TLS_AUTH_KEY: ${{ secrets.PROTONVPN_TLS_AUTH_KEY }}

      - name: Render rmd
        run: Rscript -e 'rmarkdown::render("dev/rmd_statsNBA.Rmd",output_dir = "docs",output_file = "index.html")'

      - name: Disconnect from ProtonVPN
        run: sudo killall openvpn
        if: ${{ always() }}

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/index.html
          git commit -m 'update data rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
